const CATALOGO = [
  {
    codigo: 1,
    nome: "Camisa Inter Miami Preta",
    categoria: "América do Norte",
    preco: 189.9,
    estoque: 10,
    imagem: "imagens/camisa1.jpg",
  },
  {
    codigo: 2,
    nome: "Camisa Charlotte FC Treino",
    categoria: "América do Norte",
    preco: 199.9,
    estoque: 6,
    imagem: "imagens/camisa2.jpg",
  },
  {
    codigo: 3,
    nome: "Camisa Palmeiras Verde",
    categoria: "Brasileirão",
    preco: 179.9,
    estoque: 0,
    imagem: "imagens/camisa3.jpg",
  },
  {
    codigo: 4,
    nome: "Camisa Flamengo Branca",
    categoria: "Brasileirão",
    preco: 189.9,
    estoque: 12,
    imagem: "imagens/camisa4.jpg",
  },
  {
    codigo: 5,
    nome: "Camisa Manchester City Azul",
    categoria: "Europa",
    preco: 209.9,
    estoque: 7,
    imagem: "imagens/camisa5.jpg",
  },
  {
    codigo: 6,
    nome: "Camisa Boca Juniors Azul",
    categoria: "América do Sul",
    preco: 199.9,
    estoque: 4,
    imagem: "imagens/camisa6.jpg",
  },
  {
    codigo: 7,
    nome: "Camisa Arsenal Vermelha",
    categoria: "Europa",
    preco: 219.9,
    estoque: 5,
    imagem: "imagens/camisa7.jpg",
  },
];
